trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  OutputPath: '$(build.artifactstagingdirectory)'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

#- task: VSTest@2
#  inputs:
#    platform: '$(buildPlatform)'
#    configuration: '$(buildConfiguration)'

#- task: NuGetCommand@2
#  inputs:
#    command: 'push'
#    packagesToPush: '$(build.artifactstagingdirectory)/*.nupkg'
#    nuGetFeedType: 'internal'
#    publishVstsFeed: '18a6243f-7dac-4c78-bb92-3af88cd8e255'

#- task: CopyFiles@2
#  displayName: 'Stage Artifacts'
#  inputs:
#    SourceFolder: '$(system.defaultworkingdirectory)\src\bin\Release'
#    Contents: '**'
#    TargetFolder: '$(build.artifactstagingdirectory)'
#  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
