# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $version = (Select-Xml -Path ".\package.props" -XPath "/Project/PropertyGroup/VersionBase" | Select-Object -ExpandProperty Node).InnerText
      Write-Host $version
      Write-Host "##vso[task.setvariable variable=stageVersion]$version"
      Write-Host "Trying to read $env:stageVersion"

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'git log -1 --pretty="format:%ct"'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: '$env:stagingVersion = (Select-Xml -Path ".\package.props" -XPath "/Project/PropertyGroup/VersionBase" | Select-Object -ExpandProperty Node).InnerText'

- task: CmdLine@2
  inputs:
    script: 'set'

