trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  stagingVersion: '5.11.2-$(git show -s --format=%ct)'
#  OutputPath: '$(build.artifactstagingdirectory)'

steps:
- task: CmdLine@2
  inputs:
    script: 'set'

- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'

- task: NuGetCommand@2
  displayName: 'Restore Packages'
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: 'Build Package'
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: CopyFiles@2
  displayName: 'Stage Artifacts'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)\src\bin\Release'
    Contents: '*.nupkg'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'

- task: CmdLine@2
  inputs:
    script: 'for /f %%i in ("git show -s --format=%ct") do set datetime=%%i'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: '$env:stagingVersion = (Select-Xml -Path ".\package.props" -XPath "/Project/PropertyGroup/VersionBase" | Select-Object -ExpandProperty Node).InnerText'

- task: DotNetCoreCLI@2
  displayName: 'Package Library'
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'stagingVersion'
    verbosityPack: 'Minimal'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))


#- task: NuGetCommand@2
#  displayName: 'Publish Local Feed'
#  inputs:
#    command: 'push'
#    packagesToPush: '$(build.artifactstagingdirectory)/*.nupkg'
#    nuGetFeedType: 'internal'
#    publishVstsFeed: '18a6243f-7dac-4c78-bb92-3af88cd8e255'
#    allowPackageConflicts: true
#    versioningScheme: byPrereleaseNumber
#    majorVersion: '5'
#    minorVersion: '11'
#    patchVersion: '2-1573330802'
#  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

