# Build pipeline

trigger:
- master
- refs/tags/*

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
#  OutputPath: '$(system.defaultworkingdirectory)\bin'

steps:
- task: PowerShell@2
  displayName: 'Version Info'
  inputs:
    targetType: 'inline'
    script: |
      $version = (Select-Xml -Path ".\package.props" -XPath "/Project/PropertyGroup/VersionBase" | Select-Object -ExpandProperty Node).InnerText
      $timestamp = git log -1 --pretty="format:%ct"
      Write-Host "Version: $version" 
      Write-Host "Time Stamp: $timestamp" 
      if ([regex]::IsMatch($Env:BUILD_SOURCEBRANCH, "^(refs\/tags\/v)")) { 
          Write-Host "Package Version: $($version)" 
          Write-Host "##vso[task.setvariable variable=PACKAGE_VERSION]$($version)" 
      } Else { 
          Write-Host "Package Version:$($version)-$($timestamp)" 
          Write-Host "##vso[task.setvariable variable=PACKAGE_VERSION]$($version)-$($timestamp)" 
      }

#- task: CopyFiles@2
#  displayName: 'Stage Properties'
#  inputs:
#    SourceFolder: '$(system.defaultworkingdirectory)'
#    Contents: '*.props'
#    TargetFolder: '$(build.artifactstagingdirectory)'

#- task: CopyFiles@2
#  displayName: 'Stage Source'
#  inputs:
#    SourceFolder: '$(system.defaultworkingdirectory)\src'
#    Contents: '**/**'
#    TargetFolder: '$(build.artifactstagingdirectory)\src'

#- task: PublishBuildArtifacts@1
#  displayName: 'Publish Staged Source'
#  inputs:
#    PathtoPublish: '$(build.artifactstagingdirectory)'
#    artifactName: 'Source'

- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'

- task: NuGetCommand@2
  displayName: 'Restore'
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: 'Build'
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Pack Package'
  inputs:
    command: 'pack'
    packagesToPack: 'src/*.csproj'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'PACKAGE_VERSION'
    verbosityPack: 'Minimal'

- task: CopyFiles@2
  displayName: 'Stage Package'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)\src\bin\$(buildConfiguration)'
    Contents: '**/*.nupkg'
    TargetFolder: '$(build.artifactstagingdirectory)\Package'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)\Package'
    artifactName: 'Package'

- task: NuGetCommand@2
  displayName: 'Publish Local Feed'
  inputs:
    command: 'push'
    packagesToPush: '$(build.artifactstagingdirectory)/*.$(PACKAGE_VERSION).nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '18a6243f-7dac-4c78-bb92-3af88cd8e255'
    allowPackageConflicts: true
